# Generated by Django 3.2.18 on 2023-02-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='url',
            field=models.CharField(max_length=124),
        ),
    ]
