# Generated by Django 3.2.18 on 2023-02-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_header_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=124, verbose_name='Цифры')),
                ('description', models.CharField(max_length=124, verbose_name='Описание')),
            ],
        ),
    ]
