# Generated by Django 3.2.18 on 2023-02-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_advertising'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertising',
            options={'verbose_name': 'Реклама', 'verbose_name_plural': 'Реклама'},
        ),
    ]
