# Generated by Django 3.2.18 on 2023-02-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_advertising_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertising',
            options={'verbose_name': 'Информация', 'verbose_name_plural': 'Информация'},
        ),
        migrations.AddField(
            model_name='advertising',
            name='url',
            field=models.CharField(blank=True, max_length=124),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='header',
            field=models.CharField(max_length=124, verbose_name='Заголовок'),
        ),
    ]
