# Generated by Django 3.2.18 on 2023-02-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20230220_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=124, verbose_name='Заголовок')),
                ('url', models.CharField(max_length=124)),
                ('image', models.FileField(upload_to='', verbose_name='Иконка')),
            ],
        ),
        migrations.CreateModel(
            name='InlineFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=124, verbose_name='Заголовок')),
                ('url', models.CharField(max_length=124)),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Иконка')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline', to='mysite.footer')),
            ],
        ),
    ]
