# Generated by Django 3.2.18 on 2023-02-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_footer_inlinefooter_socialnetworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworks',
            name='image',
            field=models.FileField(blank=True, upload_to='', verbose_name='Иконка'),
        ),
    ]
