# Generated by Django 3.2.18 on 2023-02-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_socialnetworks_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=124, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=124, verbose_name='Описание')),
                ('url', models.CharField(blank=True, max_length=124)),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация',
            },
        ),
        migrations.AlterModelOptions(
            name='advertising',
            options={'verbose_name': 'Преимущества', 'verbose_name_plural': 'Преимущества'},
        ),
        migrations.RemoveField(
            model_name='advertising',
            name='url',
        ),
    ]
