# Generated by Django 3.2.18 on 2023-03-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписка'},
        ),
        migrations.AddField(
            model_name='footer',
            name='div_class',
            field=models.CharField(blank=True, max_length=124),
        ),
    ]
