# Generated by Django 3.2.18 on 2023-03-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_inlinefooter_li_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='ul_class',
            field=models.CharField(blank=True, max_length=124),
        ),
    ]
