# Generated by Django 3.2.18 on 2023-03-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_footer_ul_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworks',
            name='image',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Иконка'),
        ),
    ]
