# Generated by Django 3.2.18 on 2023-03-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_alter_socialnetworks_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inlinefooter',
            name='image',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Иконка'),
        ),
    ]
