# Generated by Django 3.2.18 on 2023-03-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_alter_inlinefooter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='description',
            field=models.CharField(max_length=1240, verbose_name='Описание'),
        ),
    ]
