# Generated by Django 3.2.18 on 2023-03-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_alter_maininfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='alt',
            field=models.CharField(blank=True, max_length=124),
        ),
    ]
