# Generated by Django 3.2.18 on 2023-03-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='alt',
            field=models.CharField(blank=True, max_length=124),
        ),
        migrations.AddField(
            model_name='coins',
            name='card_info',
            field=models.CharField(blank=True, max_length=124),
        ),
        migrations.AddField(
            model_name='coins',
            name='card_information_title',
            field=models.CharField(blank=True, max_length=124),
        ),
        migrations.AddField(
            model_name='coins',
            name='div_class',
            field=models.CharField(blank=True, max_length=124),
        ),
        migrations.AddField(
            model_name='coins',
            name='p_class',
            field=models.CharField(blank=True, max_length=124),
        ),
        migrations.AlterField(
            model_name='coins',
            name='description',
            field=models.CharField(max_length=1240, verbose_name='Описание'),
        ),
    ]
