# Generated by Django 3.2.18 on 2023-03-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='text',
            field=models.TextField(),
        ),
    ]
