# Generated by Django 3.2.18 on 2023-03-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_alter_mail_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='sort',
            field=models.IntegerField(null=True),
        ),
    ]
