# Generated by Django 3.2.18 on 2023-03-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_auto_20230311_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=124)),
                ('password', models.CharField(max_length=124)),
                ('smtp_server', models.CharField(max_length=124)),
                ('port', models.IntegerField()),
            ],
        ),
    ]
