# Generated by Django 3.2.18 on 2023-03-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sender',
            options={'verbose_name': 'Отправитель рассылки', 'verbose_name_plural': 'Отправитель рассылки'},
        ),
    ]
